# generated by maixhub, tested on maixpy3 v0.4.8
# copy files to TF card and plug into board and power on
import sensor, image, lcd, time
import KPU as kpu
from machine import UART
import gc, sys
from fpioa_manager import fm

input_size = (224, 224)
labels = ['04', '05', '06', '07', '01', '02', '03']
#labels = ['stationnement', 'priorite_a_droite', 'pietons', 'ceder_le_passage', 'limitation_30', 'stop', 'start']
anchors = [1.22, 1.25, 1.53, 1.62, 0.62, 0.66, 1.0, 1.03, 0.84, 0.88]

from modules import ws2812

class Led:
    def __init__(self):
        self.led = ws2812(8,100)

        r, j, v, b, vi, blk = ((250, 0, 0),
                               (200, 32, 0),
                               (0, 128, 0),
                               (0, 0, 250),
                               (128, 0, 128),
                               (0, 0, 0))
        self.leds = (r, j, v, b, vi)

        self.set_led(blk)
        self.led.display()

    def set_let(self, ind):
        self.led.set_led(0, self.leds[ind])
        self.led.display()

    def reset_let(self):
        self.set_led(0, (0, 0, 0))
        self.led.display()


led = Led()

ind = 0

input_size = (224, 224)

class Comm:
    def __init__(self, uart):
        self.uart = uart

    def send_detect_result(self, objects, labels):
        global ind
        msg = ""
        for obj in objects:
            pos = obj.rect()
            p = obj.value()
            idx = obj.classid()
            label = labels[idx]
            # msg += "{}:{}:{}:{}:{}:{:.2f}:{}, ".format(pos[0], pos[1], pos[2], pos[3], idx, p, label)
            msg += "{}, ".format(label)
            msg = msg + "\n"
            self.uart.write(msg.encode())
        led.set_led(0, ind)
        ind = (ind + 1 ) % 5

def init_uart():
    fm.register(34, fm.fpioa.UART1_TX, force=True)
    # fm.register(35, fm.fpioa.UART1_RX, force=True)

    uart = UART(UART.UART1, 115200, 8, 0, 0, timeout=1000, read_buf_len=256)
    return uart

def main(anchors, labels = None, model_addr="/sd/m.kmodel", sensor_window=input_size, lcd_rotation=0, sensor_hmirror=False, sensor_vflip=False):
    sensor.reset()
    sensor.set_pixformat(sensor.RGB565)
    sensor.set_framesize(sensor.QVGA)
    sensor.set_windowing(sensor_window)
    sensor.set_hmirror(sensor_hmirror)
    sensor.set_vflip(sensor_vflip)
    sensor.run(1)

    uart = init_uart()
    comm = Comm(uart)

    try:
        task = None
        task = kpu.load(model_addr)
        kpu.init_yolo2(task, 0.5, 0.3, 5, anchors) # threshold:[0,1], nms_value: [0, 1]
        while(True):
            img = sensor.snapshot()
            t = time.ticks_ms()
            rotated_img = img.rotation_corr(z_rotation=90)
            objects = kpu.run_yolo2(task, rotated_img)
            t = time.ticks_ms() - t
            if objects:
                for obj in objects:
                    pos = obj.rect()
                    img.draw_rectangle(pos)
                    print(labels[obj.classid()], obj.value())
                comm.send_detect_result(objects, labels)
    except Exception as e:
        led.reset_led()
        raise e
    finally:
        if not task is None:
            kpu.deinit(task)


if __name__ == "__main__":
    try:
        main(anchors = anchors, labels=labels, model_addr=0x300000, lcd_rotation=0)
        # main(anchors = anchors, labels=labels, model_addr="/sd/model-253841.kmodel")
    except Exception as e:
        sys.print_exception(e)
#        lcd_show_except(e)
    finally:
        gc.collect()
